---
title: C26111
ms.date: 11/04/2016
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C26111
helpviewer_keywords:
- C26111
ms.assetid: 85fc740a-3bbb-41b8-a848-95e243a08da9
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: a55e9420d230ffe1dc005330710074000ff82124
ms.sourcegitcommit: 42ea834b446ac65c679fa1043f853bea5f1c9c95
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 04/19/2018
---
# <a name="c26111"></a>C26111
Advertencia C26111: no puede liberar el bloqueo de llamador \<bloqueo > antes una llamada a función \<func >.

 La anotación `_Requires_lock_not_held_` impone una condición previa que el recuento de bloqueos del bloqueo especificado no puede ser mayor que cero cuando se llama a la función. C26111 de advertencia se emite cuando se produce un error en una función liberar el bloqueo antes de llamar a otra función.

## <a name="example"></a>Ejemplo
 En el ejemplo siguiente genera la advertencia C26111 porque el `_Requires_lock_not_held_` se infringe la condición previa por la llamada a `DoNotLock` dentro de la sección bloqueada.

```

typedef struct _DATA
{
    CRITICAL_SECTION cs;
    int d;
} DATA;

_Requires_lock_not_held_(p->cs)

void DoNotLock(DATA* p)
{
    EnterCriticalSection(&p->cs);
    p->d = 0;
    LeaveCriticalSection(&p->cs);
}

void LockedFunction(DATA* p)
{
    EnterCriticalSection(&p->cs);
    DoNotLock(p); // Warning C26111
    LeaveCriticalSection(&p->cs);
}

```