---
title: C28198 | Documentos de Microsoft
ms.custom: 
ms.date: 11/04/2016
ms.reviewer: 
ms.suite: 
ms.technology: vs-ide-code-analysis
ms.tgt_pltfrm: 
ms.topic: article
f1_keywords: C28198
helpviewer_keywords: C28198
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
caps.latest.revision: "3"
author: mikeblome
ms.author: mblome
manager: ghogen
ms.openlocfilehash: 0d1c675c58505c99c035d8743e266379af588885
ms.sourcegitcommit: fb751e41929f031d1a9247bc7c8727312539ad35
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 11/15/2017
---
# <a name="c28198"></a>C28198
Advertencia C28198: posible pérdida de memoria debido a una excepción.  
  
 Esta advertencia indica que la memoria asignada no se libera después de que se produce una excepción. La instrucción al final de la ruta de acceso puede producir una excepción. La memoria se pasó a una función guardada por una copia que se libere más adelante.  
  
 Esta advertencia es muy similar a la advertencia [C28197](../code-quality/c28197.md). Las anotaciones que se recomiendan para su uso con la advertencia [C28197](../code-quality/c28197.md) también se pueden emplear.  
  
## <a name="example"></a>Ejemplo  
 El siguiente código de ejemplo genera esta advertencia:  
  
```  
char *p1 = new char[10];  
char *p2 = new char[10];  
  
test(p1);   // does not save a copy of p  
  
delete[] p2;  
delete[] p1;  
```  
  
 El siguiente código de ejemplo evita esta advertencia:  
  
```  
char *p1 = new char[10];  
char *p2 = NULL;  
  
test(p1);   // does not save a copy of p  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
```