---
title: "C28198 | Microsoft Docs"
ms.custom: ""
ms.date: "11/04/2016"
ms.reviewer: ""
ms.suite: ""
ms.technology: 
  - "vs-devops-test"
ms.tgt_pltfrm: ""
ms.topic: "article"
f1_keywords: 
  - "C28198"
helpviewer_keywords: 
  - "C28198"
ms.assetid: 8bad4acb-712c-43f5-81d1-45d92092d4c5
caps.latest.revision: 3
author: "corob-msft"
ms.author: "corob"
manager: "ghogen"
caps.handback.revision: 3
---
# C28198
[!INCLUDE[vs2017banner](../code-quality/includes/vs2017banner.md)]

Advertencia C28198: Posible pérdida de memoria debido a una excepción  
  
 Esta advertencia indica que la memoria asignada no se libera después de que se inicia una excepción.  El fragmento al final de la ruta de acceso puede provocar una excepción.  La memoria ha pasado a una función que podría haber guardado una copia que se libera más adelante.  
  
 Esta advertencia es muy similar a la advertencia [C28197](../code-quality/c28197.md).  Las anotaciones recomendadas para el uso con la advertencia [C28197](../code-quality/c28197.md) también se pueden utilizar aquí.  
  
## Ejemplo  
 El siguiente ejemplo de código genera la advertencia:  
  
```  
char *p1 = new char[10];  
char *p2 = new char[10];  
  
test(p1);   // does not save a copy of p  
  
delete[] p2;  
delete[] p1;  
```  
  
 El siguiente ejemplo de código evita la advertencia:  
  
```  
char *p1 = new char[10];  
char *p2 = NULL;  
  
test(p1);   // does not save a copy of p  
try {  
    p2 = new char[10];  
} catch (std::bad_alloc *e) {  
    // just handle the throw  
    ;  
}  
```