---
title: C6312
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.topic: reference
f1_keywords:
- C6312
helpviewer_keywords:
- C6312
ms.assetid: 1fc8b9a1-e6ba-4799-84c3-31f289576cca
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: caa2044c9bd36e8e7953bf2e7b1162f347bc8e04
ms.sourcegitcommit: 37fb7075b0a65d2add3b137a5230767aa3266c74
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 01/02/2019
ms.locfileid: "53890224"
---
# <a name="c6312"></a>C6312
Advertencia C6312: Posible bucle infinito: usar la constante EXCEPTION_CONTINUE_EXECUTION en la expresión de filtro de excepciones de try-excepto

 Esta advertencia indica que el uso de la constante `EXCEPTION_CONTINUE_EXECUTION` (u otra constante que se evalúa como -1) en la expresión de filtro de controlador de excepciones estructurado. Uso del valor constante `EXCEPTION_CONTINUE_EXECUTION` podría dar lugar a un bucle infinito. Por ejemplo, si se generó una excepción por hardware, se reiniciará la instrucción que produjo la excepción. Si la dirección que produjo la excepción sigue siendo incorrecta, otro tipo de excepción se producirá y administrarse de la misma manera. Esto hace que un bucle infinito.

 Una llamada explícita a `RaiseException` directamente no le causa un bucle infinito, pero continuará la ejecución del código en el bloque protegido. Esto puede ser inesperado y podría provocar un bucle infinito si `RaiseException` se usó para evitar la desreferenciación de un puntero no válido.

 Por lo general, `EXCEPTION_CONTINUE_EXECUTION` debe devolver una función llamada en la expresión de filtro, que tiene la oportunidad de corregir, ya sea el puntero que produjo la excepción o la memoria subyacente.

## <a name="example"></a>Ejemplo
 El código siguiente genera esta advertencia:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
   *ptr = '\0';
  }
  __except (EXCEPTION_CONTINUE_EXECUTION)
    // When EXCEPTION_CONTINUE_EXECUTION is used, the handler
    //  block of the structured exception handler is not executed.
  {
    puts("This block is never executed");
  }
}
```

 Para corregir esta advertencia, utilice el código siguiente:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

void f (char *ptr)
{
  __try
  {
    // exception occurs if the caller passes null ptr
    // code...
    *ptr = '\0';
  }
  __except (GetExceptionCode()== EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Error Occurred");
  }
}
```