---
title: C6310
ms.date: 11/04/2016
ms.prod: visual-studio-dev15
ms.technology: vs-ide-code-analysis
ms.topic: reference
f1_keywords:
- C6310
helpviewer_keywords:
- C6310
ms.assetid: e759eb63-883f-4c3e-bf2f-b924ff511405
author: mikeblome
ms.author: mblome
manager: wpickett
ms.workload:
- multiple
ms.openlocfilehash: 95445e0ed60fa5b4d52617dba5db7deb71ad1c62
ms.sourcegitcommit: e13e61ddea6032a8282abe16131d9e136a927984
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 04/26/2018
ms.locfileid: "31891311"
---
# <a name="c6310"></a>C6310
Advertencia C6310: constante no válida en el filtro de excepción puede provocar un comportamiento inesperado

 Este mensaje indica que se ha detectado una constante no válida en la expresión de filtro de un controlador de excepciones estructurado. Las constantes definidas para su uso en la expresión de filtro de un controlador de excepciones estructurado son:

-   `EXCEPTION_CONTINUE_EXECUTION`

-   `EXCEPTION_CONTINUE_SEARCH`

-   `EXCEPTION_EXECUTE_HANDLER`

 Estos valores se definen en el excpt.h de archivo de encabezado en tiempo de ejecución.

 Uso de una constante que no está en la lista anterior puede provocar un comportamiento inesperado.

## <a name="example"></a>Ejemplo
 El código siguiente genera esta advertencia:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

BOOL LimitExceeded();

void fd( )
{
  __try
  {
    if (LimitExceeded())
    {
      RaiseException(EXCEPTION_ACCESS_VIOLATION,0,0,0);
    }
    else
    {
      // code
    }
  }
  __except (EXCEPTION_ACCESS_VIOLATION)
  {
    puts("Exception Occurred");
  }
}
```

 Para corregir esta advertencia, utilice el código siguiente:

```
#include <excpt.h>
#include <stdio.h>
#include <windows.h>

BOOL LimitExceeded();

void fd( )
{
  __try
  {
    if (LimitExceeded())
    {
      RaiseException(EXCEPTION_ACCESS_VIOLATION,0,0,0);
    }
    else
    {
      // code
    }
  }
  __except (GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)
  {
    puts("Exception Occurred");
  }
}
```