---
title: C6320 | Documentos de Microsoft
ms.custom: ''
ms.date: 11/04/2016
ms.technology:
- vs-ide-code-analysis
ms.topic: conceptual
f1_keywords:
- C6320
helpviewer_keywords:
- C6320
ms.assetid: fb9e568e-b3d4-4ce2-a276-a64ad74d7b1e
author: mikeblome
ms.author: mblome
manager: douge
ms.workload:
- multiple
ms.openlocfilehash: 23e01f6034e7ca387826fd5b2bdc2e3f21bfe189
ms.sourcegitcommit: 6a9d5bd75e50947659fd6c837111a6a547884e2a
ms.translationtype: MT
ms.contentlocale: es-ES
ms.lasthandoff: 04/16/2018
---
# <a name="c6320"></a>C6320
Advertencia C6320: expresión de filtro de excepciones es la constante EXCEPTION_EXECUTE_HANDLER. Esto puede enmascarar excepciones que no se han diseñado para controlar  
  
 Esta advertencia indica que el efecto secundario de utilizar la constante EXCEPTION_EXECUTE_HANDLER en un bloque __except. En este caso, la instrucción en el \_siempre se ejecutará el bloque _except para controlar la excepción, incluidas las excepciones que desea controlar en una función determinada. Se recomienda que compruebe la excepción antes de controlarla.  
  
## <a name="example"></a>Ejemplo  
 El código siguiente genera esta advertencia porque el bloque __except intentará controlar las excepciones de todos los tipos:  
  
```  
#include <stdio.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;  // might cause access violation exception  
      // code ...  
   }   
   __except(EXCEPTION_EXECUTE_HANDLER) // warning  
   {   
      puts("in except");   
      // code ...  
   }   
}   
```  
  
 Para corregir esta advertencia, utilice `GetExceptionCode` para comprobar si una excepción determinada antes de controlarla, como se muestra en el código siguiente:  
  
```  
#include <stdio.h>   
#include <windows.h>   
#include <excpt.h>   
  
void f(int *p)   
{   
   __try  
   {   
      puts("in try");   
      *p = 13;    // might cause access violation exception   
      // code ...  
   }   
   __except(GetExceptionCode()==EXCEPTION_ACCESS_VIOLATION ?   
               EXCEPTION_EXECUTE_HANDLER : EXCEPTION_CONTINUE_SEARCH)  
   {   
      puts("in except");   
      // code ...  
   }   
}  
```  
  
## <a name="see-also"></a>Vea también  
 [try-except (Instrucción)](/cpp/cpp/try-except-statement)